### ISSUE TITLE
새로운 자가진단 사이트 오픈

### ISSUE THREAD

**Issue by MinSeungHyun** [junhoyeo/self-check-automation#10]
[hcs.eduro.go.kr](https://hcs.eduro.go.kr/)

기존엔 교육청별로 사이트가 있었는데, 이젠 하나로 통합될 것 같습니다.
기존 사이트에서 해도 데이터가 동기화 된다고 하는 것 같은데, 혹시 모르니 올려둡니다.

(+ 이제 교사들도 자가진단을 해야 한다고 들었어요)

**Comment by viokorea** [comment]
기존사이트에서 자가진단할경우 데이터가 통합되지 않는것같습니다

**Comment by MinSeungHyun** [comment]
바뀐게 좀 많아서 새로운 브랜치로 v2를 만드는게 좋겠다는 생각이 드네요. @junhoyeo

**Comment by junhoyeo** [comment]
> 바뀐게 좀 많아서 새로운 브랜치로 v2를 만드는게 좋겠다는 생각이 드네요. @junhoyeo

동의합니다! 위키 기능을 이용해 현재 통합 API를 문서화해도 좋을 것 같아요.

**Comment by junhoyeo** [comment]
- 본 레포지토리에서 [위키](https://github.com/junhoyeo/self-check-automation/wiki)를 시작했습니다.
- 현재는 [건강상태 자가진단 통합 API](https://github.com/junhoyeo/self-check-automation/wiki/%EA%B1%B4%EA%B0%95%EC%83%81%ED%83%9C-%EC%9E%90%EA%B0%80%EC%A7%84%EB%8B%A8-%ED%86%B5%ED%95%A9-API) 페이지에 비공개 API의 문서화를 시작한 상태입니다.
- 앞으로 본 레포와 위키의 방향에 대해서 더 고민해봤으면 좋겠습니다!
  - [편집을 누구나 가능하게 할지](https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis), 아니면 현재처럼 기여자에 한정해서 수정할 수 있게 할지에 대해서 고민해봐야 할 것 같아요!
  - 아니면 따로 공개 레포지토리를 만들어서 거기서 관리해도 될 것 같고요. 누구나 PR을 보낼 수 있고, 이슈도 본 프로젝트와는 별개로 관리할 수 있기 때문에 더 편할 것 같기도 합니다.

**Comment by junhoyeo** [comment]
오늘중에 업데이트해 두겠습니다.
